apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    chart: n8n
    repoURL: 'https://community-charts.github.io/helm-charts'
    targetRevision: 0.22.1
    helm:
      values: |
        config:
          encryptionKey: "my-secret-key-123"
        
        persistence:
          enabled: true
          size: 5Gi
          storageClassName: "local-path"
        
        database:
          mode: internal
        
        postgresql:
          enabled: true
          primary:
            persistence:
              enabled: true
              size: 5Gi
              storageClass: "local-path"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: n8n-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true