apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway
spec:
  project: default
  source:
    repoURL: https://github.com/Shmuel-Sayam/k8s-lab
    path: nginx-gateway
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
