apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-lab-root
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Shmuel-Sayam/k8s-lab.git
    targetRevision: main
    path: applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
  ignoreDifferences:
      - group: argoproj.io
        kind: Application
        jsonPointers:
          - /status
          - /metadata/annotations
          - /metadata/finalizers
